import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            colors: {
                "on-secondary-fixed": "#241a00",
                "on-tertiary-container": "#ff8f96",
                "on-error": "#ffffff",
                "on-surface": "#121c2a",
                "on-background": "#121c2a",
                "surface": "#f8f9ff",
                "secondary-container": "#fed255",
                "outline": "#707974",
                "surface-bright": "#f8f9ff",
                "background": "#f8f9ff",
                "on-tertiary-fixed-variant": "#822430",
                "surface-container": "#e6eeff",
                "on-secondary": "#ffffff",
                "primary": "#003426",
                "surface-container-highest": "#d9e3f6",
                "on-secondary-fixed-variant": "#584400",
                "surface-container-low": "#eff4ff",
                "on-surface-variant": "#404944",
                "primary-container": "#0f4c3a",
                "tertiary-fixed": "#ffdada",
                "inverse-on-surface": "#eaf1ff",
                "error": "#ba1a1a",
                "surface-container-lowest": "#ffffff",
                "primary-fixed-dim": "#99d3ba",
                "on-primary": "#ffffff",
                "on-primary-fixed": "#002117",
                "on-primary-container": "#82bba4",
                "surface-dim": "#d0dbed",
                "surface-variant": "#d9e3f6",
                "tertiary-fixed-dim": "#ffb3b6",
                "on-error-container": "#93000a",
                "secondary-fixed": "#ffe08e",
                "surface-tint": "#306855",
                "surface-container-high": "#dee9fc",
                "tertiary": "#5e0719",
                "outline-variant": "#bfc9c3",
                "tertiary-container": "#7d202d",
                "primary-fixed": "#b4efd6",
                "secondary-fixed-dim": "#ecc246",
                "on-primary-fixed-variant": "#15503e",
                "secondary": "#755b00",
                "on-secondary-container": "#735a00",
                "error-container": "#ffdad6",
                "on-tertiary-fixed": "#40000c",
                "inverse-primary": "#99d3ba",
                "inverse-surface": "#27313f",
                "on-tertiary": "#ffffff",
                "warm-cream": "#FBF7EE",
            },
            fontFamily: {
                sans: ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                serif: ['Playfair Display', ...defaultTheme.fontFamily.serif],
                headline: ['Playfair Display', 'serif'],
                body: ['Plus Jakarta Sans', 'sans-serif'],
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                full: '9999px',
            },
            spacing: {
                xl: '64px',
                md: '24px',
                xs: '4px',
                sm: '12px',
                gutter: '24px',
                lg: '40px',
                'container-max': '1200px',
                base: '8px',
            },
        },
    },

    plugins: [forms],
};

